### PR TITLE
""""Social Experiment""""

### PR DESCRIPTION
**Pull request by HAXORWAXOR**

### CODE REVIEW

**Comment by abashir7866** [comment]
BTC miner lol

**Comment by erxson** [comment]
foo, atomic skidder 🤑

**Comment by erxson** [comment]
@Kopamed Мне кажется что эта идея хорошая

**Comment by RaidLocked** [comment]
> Мне кажется что эта идея хорошая

is that hebrew language

**Comment by erxson** [comment]
> > Мне кажется что эта идея хорошая
> 
> is that hebrew language

its russian language

**Comment by RaidLocked** [comment]
> > > Мне кажется что эта идея хорошая
> > 
> > 
> > is that hebrew language
> 
> its russian language

no i think its hebrew

**Comment by erxson** [comment]
> > > > Мне кажется что эта идея хорошая
> > > 
> > > 
> > > is that hebrew language
> > 
> > 
> > its russian language
> 
> no i think its hebrew

no, its russian

**Comment by RaidLocked** [comment]
> > no i think its hebrew
> 
> no, its russian

are you sure

**Comment by erxson** [comment]
> > > no i think its hebrew
> > 
> > 
> > no, its russian
> 
> are you sure

no

**Comment by erxson** [comment]
havaaaaa

**Comment by RaidLocked** [comment]
> > > > no i think its hebrew
> > > 
> > > 
> > > no, its russian
> > 
> > 
> > are you sure
> 
> no

so yeah it is hebrew. i googled it

**Comment by erxson** [comment]
nagilaaaaaaaaaaaaaaaa

**Comment by Waveium** [comment]
sigma skid

**Comment by timof121** [comment]
килл юр cелф sigma hatar

**Comment by timof121** [comment]
> > > > > no i think its hebrew
> > > > 
> > > > 
> > > > no, its russian
> > > 
> > > 
> > > are you sure
> > 
> > 
> > no
> 
> so yeah it is hebrew. i googled it

Bro its russian

**Comment by Vexusz** [comment]
suck my pp

**Comment by AcaiBerii** [comment]
This code will not function and will throw an error.

Where are ```sigma```, ```blockcain``` and ```Client``` defined?  

I'd like to know please /srs

**Comment by JMRaichDev** [comment]
- Useless method 
- Malformed method
- Missing imports
- Missing methods
- Won't compile
(it's probably more a joke that an social experiment)

**Pull request closed without merging**
